### ISSUE TITLE
if fmm not installed, have kernel routines set fmm to empty. 

### ISSUE THREAD

**Issue by askhamwhat** [fastalgorithms/chunkie#53]
- like the title says, don't load fmm info into kernel if it doesn't exist on path
- put try and catch in fmm wrappers for various kernels
- print warning if forcefmm used in any routine and fmm not available

**Comment by mrachh** [comment]
This issue is closed with commit [c0f4af8](https://github.com/fastalgorithms/chunkie/commit/c0f4af8e4f96397f31d6cf78595e99473cd1b2fa)
